'use client';
import { ReactNode } from 'react';

export function Question({ number, title, helper, children }: { number: number; title: string; helper?: string; children: ReactNode }) {
  return <fieldset className="border-0 p-0 m-0 space-y-3"><legend className="w-full"><span className="text-[11px] font-bold tracking-[.16em] text-[#8b674a]">{String(number).padStart(2,'0')}</span><span className="block mt-1 text-lg md:text-xl font-semibold leading-snug">{title}</span>{helper && <span className="block mt-1 text-sm text-[#74665b] font-normal">{helper}</span>}</legend>{children}</fieldset>;
}
export function SingleChoice({ value, options, onChange }: { value?: string; options: string[]; onChange: (v:string)=>void }) {
  return <div className="grid gap-2 sm:grid-cols-2">{options.map(o => <button type="button" key={o} aria-pressed={value===o} onClick={()=>onChange(o)} className={`choice min-h-12 rounded-xl border px-4 py-3 text-left text-sm ${value===o?'border-[#5d4635] bg-[#eadbc9]':'border-[#ddd2c6] bg-white/60 hover:border-[#b99a7d]'}`}><span className={`mr-3 inline-flex h-4 w-4 rounded-full border align-[-2px] ${value===o?'border-[5px] border-[#5d4635]':'border-[#b9aa9b]'}`}/>{o}</button>)}</div>;
}
export function MultiChoice({ value=[], options, onChange, max }: { value?: string[]; options: string[]; onChange:(v:string[])=>void; max?:number }) {
  const toggle=(o:string)=>{ const next=value.includes(o)?value.filter(x=>x!==o):(!max||value.length<max?[...value,o]:value); onChange(next); };
  return <div className="grid gap-2 sm:grid-cols-2">{options.map(o => <button type="button" key={o} aria-pressed={value.includes(o)} onClick={()=>toggle(o)} className={`choice min-h-12 rounded-xl border px-4 py-3 text-left text-sm ${value.includes(o)?'border-[#5d4635] bg-[#eadbc9]':'border-[#ddd2c6] bg-white/60 hover:border-[#b99a7d]'}`}><span className={`mr-3 inline-flex h-4 w-4 items-center justify-center rounded-[5px] border text-[10px] ${value.includes(o)?'border-[#5d4635] bg-[#5d4635] text-white':'border-[#b9aa9b]'}`}>{value.includes(o)?'✓':''}</span>{o}</button>)}</div>;
}
export function RatingScale({ value, onChange }: { value?:string; onChange:(v:string)=>void }) { return <div><div className="grid grid-cols-5 sm:grid-cols-10 gap-2">{Array.from({length:10},(_,i)=>String(i+1)).map(n=><button type="button" key={n} aria-pressed={value===n} onClick={()=>onChange(n)} className={`aspect-square rounded-xl border font-semibold ${value===n?'border-[#5d4635] bg-[#5d4635] text-white':'border-[#d8cdc2] bg-white/70'}`}>{n}</button>)}</div><div className="flex justify-between mt-2 text-xs text-[#7d6f64]"><span>Not at all</span><span>Extremely</span></div></div>; }
export function TextInput({ value, onChange, placeholder, multiline=false }: { value?:string; onChange:(v:string)=>void; placeholder?:string; multiline?:boolean }) { const cn="w-full rounded-xl border border-[#d8cdc2] bg-white/70 px-4 py-3 outline-none focus:border-[#6d523e] focus:ring-2 focus:ring-[#d8b98a]/40"; return multiline?<textarea rows={3} className={cn} value={value||''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:<input className={cn} value={value||''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>; }
